Yeet and intake file
FRC3636/bunnybots-2023 pull request #1
Opened 2023-10-18 20:07 UTC by Fishhkabob

I renamed shooter to yeeter and consequently everything else as well as creating the intake file (not written yet)

2023-10-18 20:12 UTC, max-niederman requested changes

2023-10-18 20:12 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/yeeter/Yeeter.kt
> +        Logger.getInstance().recordOutput("Shooter/YeetMainMotorVelocity", io.getSpeedMain())
We should rename the logger keys to be consistent with the new name.

2023-10-18 20:12 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/yeeter/YeeterIO.kt
> +        var yeetMainVelocity = 0.0
Why add the `yeet` prefix? It seems already clear since these are the `Yeeter` inputs.

2023-10-18 20:12 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/yeeter/YeeterIO.kt
> +    private val yeetMainMotor = WPI_TalonFX(yeetSecondaryMotorCAN.id)
Same as above, but this is also inconsistent between the two motors.

2023-10-18 20:12 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/yeeter/YeeterIO.kt
> +    var yeetMainVelocity = Rotation2d()
Same as with the raw inputs.

2023-10-18 20:31 UTC, Fishhkabob commented
prefix removed

2023-10-18 22:52 UTC, max-niederman approved these changes

2023-10-18 22:56 UTC, max-niederman requested changes
Change variable names.

2023-10-19 01:33 UTC, max-niederman approved these changes
LGTM

2023-10-19 01:33 UTC, merged