feat: add bindings for and refactor various subsystems
FRC3636/bunnybots-2023 pull request #20
Opened 2023-11-22 23:26 UTC by doinkythederp

2023-11-29 02:46 UTC, max-niederman requested changes

2023-11-29 02:46 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/shooter/Shooter.kt
> +        println("debug: shooter periodic")
This should be removed.

2023-11-29 02:46 UTC, max-niederman commented on src/main/java/frc/robot/commands/DoNothingCommand.kt
I don't think this should be a custom command in our codebase since it's just for a placeholder.

2023-11-29 02:46 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/indexer/Indexer.kt
> +    object AutoIndexCommand: SequentialCommandGroup (
This should really be a class, not an object. It would be easy to accidentally schedule it twice.

2023-11-29 02:46 UTC, max-niederman commented on src/main/java/frc/robot/subsystems/intake/Intake.kt
> +        val className = this.javaClass.name
It would probably be nicer to use an abstract property instead of reflection.

2023-12-06 02:42 UTC, Gavin-Niederman approved these changes
LGTM!!!! (Lets get that money) ( :D )

2023-12-06 02:58 UTC, max-niederman requested changes

2023-12-06 02:58 UTC, max-niederman commented on src/main/java/frc/robot/RobotContainer.kt
> +//        Turret.defaultCommand = DoNothingCommand(setOf(Turret))
Uncomment these at least in real life.

2023-12-06 02:58 UTC, max-niederman commented on src/main/java/frc/robot/RobotContainer.kt
> +        JoystickButton(controller, XboxController.Button.kLeftBumper.value).onTrue(
Should use right Xbox joystick or something.

2023-12-06 02:58 UTC, max-niederman commented on src/main/java/frc/robot/RobotContainer.kt
> +        JoystickButton(controller, XboxController.Button.kA.value)
These should take Shooter as a requirement.

2023-12-06 03:15 UTC, max-niederman approved these changes

2023-12-06 03:16 UTC, merged